In [36]:
import numpy as np 


data_in = np.array([[0,1,2],[8,3,9],[4,6,9],[7,6,9]], dtype = np.float64)
with open('data.bin','wb') as f:
    f.write(data_in)
print(data_in)

[[0. 1. 2.]
 [8. 3. 9.]
 [4. 6. 9.]
 [7. 6. 9.]]
